repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff
        name: ruff (linting)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.4
    hooks:
      - id: ruff-format
        name: ruff (formatting)

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.18.0
    hooks:
      - id: ggshield
        name: ggshield
        language_version: python3
        stages: [commit]

  - repo: local
    hooks:
      - id: tests
        name: run tests
        stages: [commit]
        types: [python]
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
