repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  
  - repo: local
    hooks:
      - id: tests
        name: run tests
        stages: [commit]
        types: [python]
        entry: make test
        language: system
        pass_filenames: false
        always_run: true

  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.291
    hooks:
      - id: ruff
  # Run the Ruff formatter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.291
    hooks:
      - id: ruff-format

  
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.18.0
    hooks:
      - id: ggshield
        name: ggshield
        language_version: python3
        stages: [commit]