"""empty message

Revision ID: 8e468ec508e2
Revises: 1ef128c2e4fd
Create Date: 2023-01-07 18:28:46.995654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e468ec508e2'
down_revision = '1ef128c2e4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publicId', sa.Text(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publicId')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publicId', sa.Text(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('productId', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('ordered', sa.Boolean(), nullable=False),
    sa.Column('createAt', sa.DateTime(), nullable=False),
    sa.Column('orderDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['productId'], ['product.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publicId')
    )
    op.create_table('cartOrder',
    sa.Column('cartId', sa.Integer(), nullable=True),
    sa.Column('orderId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cartId'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['orderId'], ['order.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cartOrder')
    op.drop_table('order')
    op.drop_table('cart')
    # ### end Alembic commands ###
