version: '3'

name: easyeats

services:

  api: 
    build: 
      context: .
      dockerfile: ./compose/prod/api/Dockerfile
    image: easy-eats-api
    container_name: easy-eats-api
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 5000:5000
    command: /start
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: easyeats-db
    env_file: 
      - ./.env
    volumes:
      - data_db:/var/lib/postgresql/data


volumes:
  data_db: {}