version: '3'

name: ecommerce

services:

  api: 
    build: 
      context: .
      dockerfile: ./compose/prod/api/Dockerfile
    image: ecommerce-api
    container_name: ecommerce-api
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - 5000:5000
    command: /start
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres
    env_file: 
      - ./.env
    volumes:
      - data_db:/var/lib/postgresql/data


volumes:
  data_db: {}